version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nestdb
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
volumes:
  db-data: